#!/usr/bin/env sh

swayidle -w timeout 300 'swaylock -f -c 000000 --clock --screenshots --effect-blur 7x5' \
            timeout 600 'systemctl suspend' \
            before-sleep 'swaylock -f -c 000000 --clock --screenshots --effect-blur 7x5' &

