empty_line = false

format = """\
  $battery\
  $username\
  $hostname\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $line_break\
  $character\
  $docker_context\
"""
[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

[docker_context]
format = "via [🐋 $context](blue bold)"

[character]
success_symbol = "[-->](bold white)"
error_symbol = "[!==](bold magenta)"
vicmd_symbol = "[</>](bold cyan)"

