require("bryan.launch")
require("bryan.options")
require("bryan.keybindings")
require("bryan.autocmds")

spec("bryan.colorscheme")
spec("bryan.junk-drawer")
spec("bryan.web-devicons")
spec("bryan.typescript")
spec("bryan.treesitter")
spec("bryan.mason")
spec("bryan.lspconfig")
spec("bryan.none-ls")
spec("bryan.telescope")
spec("bryan.telescope-tabs")
-- spec("bryan.neotree")
-- spec("bryan.nvim-tree")
spec("bryan.lualine")
spec("bryan.bufferline")
spec("bryan.which-key")
spec("bryan.cmp")
spec("bryan.autopairs")
spec("bryan.comment")
spec("bryan.version-control")
spec("bryan.dashboard")
spec("bryan.surround")
spec("bryan.auto-session")
spec("bryan.colorizer")
spec("bryan.dressing")
spec("bryan.notify")
spec("bryan.harpoon")
spec("bryan.formatting")
spec("bryan.linting")
spec("bryan.orgmode")
spec("bryan.vim-maximizer")
spec("bryan.project")
spec("bryan.oil")

require("bryan.lazy")
