(DEFINE-CONFIGURATION WEB-BUFFER
  ((DEFAULT-NEW-BUFFER-URL "https://duckduckgo.com")))
(DEFINE-CONFIGURATION BUFFER
  ((CURRENT-ZOOM-RATIO 1.3)))
(SETF (UIOP/OS:GETENV "WEBKIT_DISABLE_COMPOSITING_MODE") "1")
(DEFINE-CONFIGURATION WEB-BUFFER
  ((DEFAULT-NEW-BUFFER-URL "bryanparonto.com")))
(DEFINE-CONFIGURATION WEB-BUFFER
  ((DEFAULT-NEW-BUFFER-URL "https://bryanparonto.com")))
