package = "awesome"
version = "dev-1"
source = {
   url = "git+ssh://git@github.com/apisandipas/dotfiles.git"
}
description = {
   homepage = "*** please enter a project homepage ***",
   license = "*** please specify a license ***"
}
build = {
   type = "builtin",
   modules = {
      ["freedesktop.desktop"] = "freedesktop/desktop.lua",
      ["freedesktop.init"] = "freedesktop/init.lua",
      ["freedesktop.menu"] = "freedesktop/menu.lua",
      ["lain.helpers"] = "lain/helpers.lua",
      ["lain.init"] = "lain/init.lua",
      ["lain.layout.cascade"] = "lain/layout/cascade.lua",
      ["lain.layout.centerwork"] = "lain/layout/centerwork.lua",
      ["lain.layout.init"] = "lain/layout/init.lua",
      ["lain.layout.termfair"] = "lain/layout/termfair.lua",
      ["lain.util.dkjson"] = "lain/util/dkjson.lua",
      ["lain.util.init"] = "lain/util/init.lua",
      ["lain.util.markup"] = "lain/util/markup.lua",
      ["lain.util.menu_iterator"] = "lain/util/menu_iterator.lua",
      ["lain.util.quake"] = "lain/util/quake.lua",
      ["lain.util.separators"] = "lain/util/separators.lua",
      ["lain.widget.alsa"] = "lain/widget/alsa.lua",
      ["lain.widget.alsabar"] = "lain/widget/alsabar.lua",
      ["lain.widget.bat"] = "lain/widget/bat.lua",
      ["lain.widget.cal"] = "lain/widget/cal.lua",
      ["lain.widget.contrib.init"] = "lain/widget/contrib/init.lua",
      ["lain.widget.contrib.moc"] = "lain/widget/contrib/moc.lua",
      ["lain.widget.contrib.redshift"] = "lain/widget/contrib/redshift.lua",
      ["lain.widget.contrib.task"] = "lain/widget/contrib/task.lua",
      ["lain.widget.contrib.tp_smapi"] = "lain/widget/contrib/tp_smapi.lua",
      ["lain.widget.cpu"] = "lain/widget/cpu.lua",
      ["lain.widget.fs"] = "lain/widget/fs.lua",
      ["lain.widget.imap"] = "lain/widget/imap.lua",
      ["lain.widget.init"] = "lain/widget/init.lua",
      ["lain.widget.mem"] = "lain/widget/mem.lua",
      ["lain.widget.mpd"] = "lain/widget/mpd.lua",
      ["lain.widget.net"] = "lain/widget/net.lua",
      ["lain.widget.pulse"] = "lain/widget/pulse.lua",
      ["lain.widget.pulsebar"] = "lain/widget/pulsebar.lua",
      ["lain.widget.sysload"] = "lain/widget/sysload.lua",
      ["lain.widget.temp"] = "lain/widget/temp.lua",
      ["lain.widget.weather"] = "lain/widget/weather.lua",
      rc = "rc.lua",
      ["themes.blackburn.theme"] = "themes/blackburn/theme.lua",
      ["themes.bungle.theme"] = "themes/bungle/theme.lua",
      ["themes.copland.theme"] = "themes/copland/theme.lua",
      ["themes.dremora.theme"] = "themes/dremora/theme.lua",
      ["themes.holo.theme"] = "themes/holo/theme.lua",
      ["themes.multicolor.theme"] = "themes/multicolor/theme.lua",
      ["themes.powerarrow-dark.theme"] = "themes/powerarrow-dark/theme.lua",
      ["themes.powerarrow.binclock"] = "themes/powerarrow/binclock.lua",
      ["themes.powerarrow.theme"] = "themes/powerarrow/theme.lua",
      ["themes.rainbow.theme"] = "themes/rainbow/theme.lua",
      ["themes.steamburn.theme"] = "themes/steamburn/theme.lua",
      ["themes.vertex.theme"] = "themes/vertex/theme.lua"
   }
}
