#! /bin/sh

## Reset Everything -------------------------------#
bapc rule -r "*"

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors


## Global Settings -------------------------------#
bspc config focused_border_color "$GREEN"
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$YELLOW"
bspc config border_width         2
bspc config window_gap          16
bspc config top_padding          32
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

if [[ $(xrandr -q | grep "HDMI1 connected" ) ]]; then
	bspc monitor HDMI1 -d 1 2 3 4 5
	bspc monitor eDP1 -d 6 7 8 9 0
else
	bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0
fi

bspc rule -a kitty desktop='^1'
bspc rule -a Ferdi desktop='^2'
bspc rule -a obsidian desktop='^3'
bspc rule -a Thunderbird desktop='^4'
bspc rule -a Brave-browser desktop='^5'
bspc rule -a Zoom desktop='^6'
bspc rule -a GitKraken desktop='^7'
bspc rule -a Spotify desktop='^8'
bspc rule -a dropbox state=floating manage=off

## Kickoff -------------------------------#

# Kill if already running
killall -9 gpclient volumeicon ferdi kitty thunderbird gitkraken sxhkd brave dunst xfce4-power-manager obsidian-insider

# Fire up on start/restart
gpclient &
sxhkd &
kitty -e tmux &
ferdi &
brave &
thunderbird &
gitkraken &
obsidian-insider &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nm-applet &
# dropbox &
volumeicon &
blueman-applet &
xautolock -time 120 -locker 'betterlockscreen -l dim' &
~/.config/polybar/launch.sh &
fix_xcursor &
picom -b --config ~/.config/picom/picom.conf

# Restore wallpaper
bash $HOME/.fehbg

# Lauch notification daemon
dunst \
-geom "280x50-10+38" -frame_width "1" -font "OperatorMono Nerd Font 14" \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &


