#! /bin/sh

## Reset Everything -------------------------------#
bspc rule -r "*"

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:' | awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:' | awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:' | awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:' | awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:' | awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:' | awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:' | awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:' | awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:' | awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:' | awk '{print $NF}')
}
getcolors

## Global Settings -------------------------------#
bspc config focused_border_color "$GREEN"
# bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$YELLOW"
bspc config border_width 4
bspc config border_radius 4
bspc config window_gap 32
bspc config window_border_radius 30
bspc config top_padding 32
bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

xrandr --output eDP-1 --mode 1920x1080 --auto \
	--output DVI-I-1-1 --left-of eDP-1 --rotate right --mode 1920x1080 --auto \
	--output DVI-I-2-2 --mode 1920x1080 --left-of DVI-I-1-1 --auto

if [[ $(xrandr -q | grep "DVI-I-2-2 connected") ]]; then
	bspc monitor DVI-I-1-1 -d I II III
	bspc monitor DVI-I-2-2 -d IV V VI VII
	bspc monitor eDP-1 -d VIII IX X
else
	xrandr --output eDP-1 --mode 1920x1080
	bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
fi

bspc rule -a Emacs state=tiled desktop='^1'
bspc rule -a kitty desktop='^2'
# bspc rule -a obsidian desktop='^3'
bspc rule -a Thunderbird desktop='^4'
bspc rule -a Slack desktop='^5'
bspc rule -a Zoom desktop='^5'
bspc rule -a Brave-browser desktop='^6'
bspc rule -a firefox desktop='^6'
bspc rule -a GitKraken desktop='^7'
bspc rule -a spotify desktop='^8'
bspc rule -a dropbox state=floating manage=off

## Kickoff -------------------------------#

# Kill if already running
killall polybar

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Fire up on start/restart
pgrep -x sxhkd >/dev/null || sxhkd &
pgrep -x kitty >/dev/null || kitty &
pgrep -x firefox >/dev/null || firefox &
pgrep -x pasystray >/dev/null || pasystray &
pgrep -x nm-applet >/dev/null || nm-applet &
pgrep -x blueman-applet >/dev/null || blueman-applet &
~/.config/polybar/launch.sh &
pgrep -x lockscreen-setup >/dev/null || lockscreen-setup &
pgrep -x fix-touchscreen >/dev/null || fix-touchscreen &
pgrep -x fix_xcursor >/dev/null || fix_xcursor &

# pgrep -x emacs >/dev/null ||
killall emacs
emacs --daemon --with-profile default &
# pgrep -c emacsclient >/dev/null || emacsclient -c -s default -a emacs &

# Restore wallpaper
bash $HOME/.fehbg

# Start Agenda Server
killport 8989
serve ~/org/brain/bins/agenda -p 8989 &

# Lauch notification daemon
dunst \
	-geom "380x50-10+38" -frame_width "1" -font "Victor Mono Medium 14" \
	-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
	-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
	-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &
