splash = false
# preload = ~/.dotfiles/etc/wallpaper/deskstripes.png
# wallpaper = eDP-1,~/.dotfiles/etc/wallpaper/deskstripes.png
#wallpaper = DP-1,~/Dropbox/wallpaper/island.jpg
#wallpaper = DP-2,~/Dropbox/wallpaper/island.jpg
#wallpaper = DP-3,~/Dropbox/wallpaper/island.jpg

wallpaper {
  monitor = eDP-1
  path = ~/.dotfiles/etc/wallpaper/deskstripes.png
  fit_mode = cover
}
