#!/bin/sh
feh --no-fehbg --bg-fill '/home/bryan/.dotfiles/etc/wallpaper/nebula2.jpg' '/home/bryan/.dotfiles/etc/wallpaper/nebula.jpg' '/home/bryan/.dotfiles/etc/wallpaper/hubble-monkey-head-nebula.jpg' '/home/bryan/.dotfiles/etc/wallpaper/island.jpg' 
