[colors.primary]
background = "#2d353b"
foreground = "#d3c6aa"

[colors.cursor]
cursor = "#d3c6aa"
text = "#2d353b"

[colors.selection]
background = "#543a48"
text = "#d3c6aa"

[colors.normal]
black = "#475258"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#83c092"
white = "#d3c6aa"

[colors.bright]
black = "#475258"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#83c092"
white = "#d3c6aa"
