#### ~~~~ Locale ~~~~ ####
export LANG=en_US.UTF-8

#### ~~~~ History Config ~~~~ ####
[ -z "$HISTFILE" ] && HISTFILE="$XDG_CACHE_HOME/.zsh_history"
[ "$HISTSIZE" -lt 50000 ] && HISTSIZE=50000
[ "$SAVEHIST" -lt 10000 ] && SAVEHIST=10000

#### ~~~~ History command configuration ~~~~ ####
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt share_history          # share command history data

#### ~~~~ Import ~~~~ ####
ALIAS_LOCATION="$XDG_CONFIG_HOME/zsh/zsh_aliases"
FUNCTION_LOCATION="$XDG_CONFIG_HOME/zsh/zsh_functions"
source $ALIAS_LOCATION
source $FUNCTION_LOCATION


#### ~~~~ Autostart ~~~~ #####
ufetch
